name: safecd

on: 
  push:
    branches:
      - master
  schedule:
    - cron:  '*/15 * * * *'

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: safecd
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: kilnfi/safecd@1.0.2
        id: safecd
        with:
          rpc: ${{ secrets.RPC }}
        env:
          UPLOAD: true
      - if: steps.safecd.outputs.hasChanges == 'true'
        run: |
          git config --global user.email "safecd@kiln.fi"
          git config --global user.name "safecd"
          git add --all
          git commit -F ./COMMIT_MSG
          git push
