name: safecd_pr

on: 
  pull_request:
    branches:
      - master

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: safecd_pr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.PAT }}
      - uses: kilnfi/safecd@1.0.3-rc.29
        id: safecd
        with:
          rpc: ${{ secrets.RPC }}
      - name: Comment PR
        if: ${{ steps.safecd.outputs.hasPrComment == 'true' }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: ./PR_COMMENT
          comment_tag: 'safecd'
      - name: Check failed proposals
        if: ${{ steps.safecd.outputs.hasFailedProposals == 'true' }}
        run: |
          echo "crashing ci due to failed proposal simulations"
          exit 1
